/**
 * Aggregates every module manifest into registry.json — the internal
 * catalogue of composable modules. Run with: pnpm registry
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { manifestToRegistryEntry } from "../packages/config/src/index";
import { manifest as onboarding } from "../packages/modules/onboarding/src/module.config";
import { manifest as requests } from "../packages/modules/requests/src/module.config";
import { manifest as messages } from "../packages/modules/messages/src/module.config";
import { manifest as billing } from "../packages/modules/billing/src/module.config";
import { manifest as marketing } from "../packages/modules/marketing/src/module.config";
import { manifest as documents } from "../packages/modules/documents/src/module.config";
import { manifest as website } from "../packages/modules/website/src/module.config";

const modules = [onboarding, requests, messages, billing, marketing, documents, website];

const registry = {
  $comment: "Generated by `pnpm registry` — do not edit by hand.",
  modules: modules.map(manifestToRegistryEntry),
};

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
writeFileSync(join(root, "registry.json"), JSON.stringify(registry, null, 2) + "\n");
console.log(`registry.json written (${modules.length} modules).`);
